In [2]:
import polars as pl
from polars import *

In [7]:
from pyspark.sql import SparkSession

In [24]:
demand_classical_set = pl.DataFrame(
    [
        (0,16),
        (0,17),
        (0,18),
        (0,19),
        (0,20),
        (1,21),
        (1,22),
        (1,23),
    ],
    ['high_demand', 'demand']
    ,orient='row'
)

In [25]:
demand_classical_set

shape: (8, 2)
┌─────────────┬────────┐
│ high_demand ┆ demand │
│ ---         ┆ ---    │
│ i64         ┆ i64    │
╞═════════════╪════════╡
│ 0           ┆ 16     │
│ 0           ┆ 17     │
│ 0           ┆ 18     │
│ 0           ┆ 19     │
│ 0           ┆ 20     │
│ 1           ┆ 21     │
│ 1           ┆ 22     │
│ 1           ┆ 23     │
└─────────────┴────────┘

In [26]:
demand_fuzzy_set = pl.DataFrame(
    [
        (0,16),
        (0.2,17),
        (0.4,18),
        (0.6,19),
        (0.8,20),
        (1,21),
        (1,22),
        (1,23),
    ],
    ['high_demand', 'demand']
    ,orient='row'
)

In [27]:
demand_fuzzy_set

shape: (8, 2)
┌─────────────┬────────┐
│ high_demand ┆ demand │
│ ---         ┆ ---    │
│ f64         ┆ i64    │
╞═════════════╪════════╡
│ 0.0         ┆ 16     │
│ 0.2         ┆ 17     │
│ 0.4         ┆ 18     │
│ 0.6         ┆ 19     │
│ 0.8         ┆ 20     │
│ 1.0         ┆ 21     │
│ 1.0         ┆ 22     │
│ 1.0         ┆ 23     │
└─────────────┴────────┘

In [22]:
trapezoid_function = pl.DataFrame(
    [
        (0,0),
        (2,0),
        (4,0.2),
        (6,0.4),
        (8,0.6),
        (10,0.8),
        (12,1),
        (14,0.8),
        (16,0.6),
        (18,0.4),
        (20,0.2),
        (22,0),
        (24,0),
    ],
    ['demand', 'mediocre_demand']
    ,orient='row'
)

In [23]:
trapezoid_function

shape: (13, 2)
┌────────┬─────────────────┐
│ demand ┆ mediocre_demand │
│ ---    ┆ ---             │
│ i64    ┆ f64             │
╞════════╪═════════════════╡
│ 0      ┆ 0.0             │
│ 2      ┆ 0.0             │
│ 4      ┆ 0.2             │
│ 6      ┆ 0.4             │
│ 8      ┆ 0.6             │
│ …      ┆ …               │
│ 16     ┆ 0.6             │
│ 18     ┆ 0.4             │
│ 20     ┆ 0.2             │
│ 22     ┆ 0.0             │
│ 24     ┆ 0.0             │
└────────┴─────────────────┘

In [3]:
demand_for_partitioning = pl.DataFrame(
    range(0,100),
    ['demand'],
    orient='row'
)

In [19]:
fuzzy_sets = pl.DataFrame(
    [
        (0,1,0,0,0,0),
        (25,0,1,0,0,0),
        (50,0,0,1,0,0),
        (75,0,0,0,1),
        (100,0,0,0,0),
        ],
    ['demand', 'very_low_demand','low_demand','medium_demand','high_demand','very_high_demand']
    ,orient='row'
)

In [20]:
fuzzy_sets

shape: (5, 6)
┌────────┬─────────────────┬────────────┬───────────────┬─────────────┬──────────────────┐
│ demand ┆ very_low_demand ┆ low_demand ┆ medium_demand ┆ high_demand ┆ very_high_demand │
│ ---    ┆ ---             ┆ ---        ┆ ---           ┆ ---         ┆ ---              │
│ i64    ┆ i64             ┆ i64        ┆ i64           ┆ i64         ┆ i64              │
╞════════╪═════════════════╪════════════╪═══════════════╪═════════════╪══════════════════╡
│ 0      ┆ 1               ┆ 0          ┆ 0             ┆ 0           ┆ 0                │
│ 25     ┆ 0               ┆ 1          ┆ 0             ┆ 0           ┆ 0                │
│ 50     ┆ 0               ┆ 0          ┆ 1             ┆ 0           ┆ 0                │
│ 75     ┆ 0               ┆ 0          ┆ 0             ┆ 1           ┆ 0                │
│ 100    ┆ 0               ┆ 0          ┆ 0             ┆ 0           ┆ 1                │
└────────┴─────────────────┴────────────┴───────────────┴─────────────┴──────────────────┘